#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /
    controller: App\Controller\ArticleController::index
    
kapelmistrz:
    path: /kapelmistrz
    controller: App\Controller\ArticleController::kapelmistrz
